### ISSUE TITLE
need some help

### ISSUE THREAD

**Issue by chocosobo** [ya-kmet/dota2-static#1]
im stuck at 

~~~
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `dota2-static.gemspec`: uninitialized constant Dota2::Static::Hero. Bundler cannot continue.

 #  from C:/Users/sobo/Documents/dota2-static/dota2-static.gemspec:27
 #  -------------------------------------------
 #
 >  end
 #  # coding: utf-8
 #  -------------------------------------------
. Bundler cannot continue.
~~~

adding 

~~~
Dota2::Static::Hero.all               # => [Dota2::Static::Hero]
hero.abilities                        # => [Dota2::Static::Ability]
image_tag hero.image_lg               # => HTML image tag for 205x115 version
image_tag hero.image_full             # => HTML image tag for 256x144 version
~~~

under end on file 'dota2-static.gamespec'

i try to get some new skill images like slark,
and changed image like fluffy hat, astral step, etc

but stuck at this error

**Comment by ya-kmet** [comment]
> under end on file 'dota2-static.gamespec'

Sorry for my very late answer :)

Looks like you try to add your code to gemspec file, which is not supposed to happen.

To use the gem add it to your Gemfile, like it is said in README and use it like any other gem in ruby world.
